### ISSUE TITLE
Implement Gain_Ratio()

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/chainsaw#2]
**Prerequisite Issues**

- [x] #1 

**Overview of this Issue**

The signature of the `gain_ratio_split()` function was designed in #1. To implement it, a few more tasks need to be completed.

**Tasks to Close Issue**

- [x] Describe the parameters in more detail. Post the descriptions as a reply to this issue.
- [x] Design unit tests for this function. Post it as a reply to this issue.
- [x] Implement the unit tests.
- [x] Implement `gain_ratio_split()`.
- [x] Ensure that `gain_ratio_split()` passes its unit tests.
- [x] Generate documentation.

**Comment by mikesiers** [comment]
*Function Signature*

gain_ratio_split(node, minimum_records) : wattle.Test

*Parameters*

- node - wattle.Node object for which the best gain ratio will be found.
- minimum_records - float for the minimum records in a leaf constraint.

*Return Value*

A wattle.Test object which describes the split which achieves the best gain ratio. Returns `None` if there isn't a split that is good enough.

**Comment by mikesiers** [comment]
*Unit Tests*

- Test that the correct best split is found for a dataset with one numerical attribute.
- Test that the correct best split is found when minimum_records is changed.

**Comment by mikesiers** [comment]
The unit tests have been changed to accommodate a MVP. Therefore, only numerical attributes will be supported for now.

**Comment by mikesiers** [comment]
This work was completed in PR #5.
