### ISSUE TITLE
Implement Ultimate_Gain_Ratio()

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/chainsaw#3]
**Prerequisite Issues**

- [x] #1 

**Overview of this Issue**

The signature of the `ultimate_gain_ratio_split()` function was designed in #1. To implement it, a few more tasks need to be completed.

**Tasks to Close Issue**

- [x] Describe the parameters in more detail. Post the descriptions as a reply to this issue.
- [x] Design unit tests for this function. Post it as a reply to this issue.
- [ ] Implement the unit tests.
- [ ] Implement `ultimate_gain_ratio_split()`.
- [ ] Ensure that `ultimate_gain_ratio_split()` passes its unit tests.
- [ ] Generate documentation.

**Comment by mikesiers** [comment]
*Function Signature*

ultimate_gain_ratio_split(node, minimum_gain, minimum_leaves) : wattle.Test

*Parameters*

- node - wattle.Node object for which the best ultimate gain ratio will be found.
- minimum_records - float for the minimum records in a leaf constraint.

*Return Value*

A wattle.Test object which describes the split which achieves the best ultimate gain ratio.

**Comment by mikesiers** [comment]
*Unit Tests*

- Test that the correct best split is found for a dataset with one numerical attribute.
- Test that the correct best split is found for a dataset with one categorical attribute.
- Test that the correct best split is found for a dataset with one numerical attribute.
- Test that the correct best split is found when minimum_records is changed.

**Comment by mikesiers** [comment]
This functionality has been cut from the initial release of chainsaw.
