### ISSUE TITLE
Implement Cost_Reduction()

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/chainsaw#4]
**Prerequisite Issues**

- [x] #1 

**Overview of this Issue**

The signature of the `cost_reduction_split()` function was designed in #1. To implement it, a few more tasks need to be completed.

**Tasks to Close Issue**

- [x] Describe the parameters in more detail. Post the descriptions as a reply to this issue.
- [x] Design unit tests for this function. Post it as a reply to this issue.
- [x] Implement the unit tests.
- [x] Implement `cost_reduction_split()`.
- [x] Ensure that `cost_reduction_split()` passes its unit tests.
- [x] Generate documentation.

**Comment by mikesiers** [comment]
*Function Signature*

cost_reduction_split(node, positive_class, cost_matrix) : wattle.Test

*Parameters*

- node - wattle.Node object for which the best ultimate gain ratio will be found.
- positive_class - a string of the positive class' name.
- cost_matrix - a dictionary of the costs in the cost matrix. e.g., {'TP' : 1, 'TN' : 0, 'FP' : 1, 'FN' : 5}

*Return Value*

A wattle.Test object which describes the split which achieves the best cost reduction. Returns `None` if there isn't a split that is good enough.

**Comment by mikesiers** [comment]
*Unit Tests*

- Test that the correct best split is found for a simple SDP dataset.

**Comment by mikesiers** [comment]
The unit tests have been changed to accommodate a MVP. Therefore, only numerical attributes will be supported for now.
