### ISSUE TITLE
Upload to PyPi

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/chainsaw#6]
**Overview of this Issue**

To make chainsaw available via 'pip install PyPi' and then importable via 'import chainsaw', it should be uploaded to PyPi. This requires some setup.

**Tasks to Close Issue**

- [x] Move chainsaw.py to root folder and delete src folder.
- [x] Create setup.py and setup.cfg.
- [x] Merge the above into master.
- [x] Create release.
- [x] Upload to PyPi.

**Comment by mikesiers** [comment]
https://pypi.python.org/pypi/chainsaw/1.00
